/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modèle.Resultset;

/**
 *
 * @author leand
 */
public class Interface_eleve extends javax.swing.JFrame {

    /**
     * Creates new form Interface_eleve
     * @param jLabel2
     * @param jLabel4
     */
    String nom;
    String prenom;
    
    public Interface_eleve(String jLabel2, String jLabel4) {
        initComponents();
        this.nom = jLabel2;
        this.prenom = jLabel4;
    }
    
    private Interface_eleve() {
        initComponents();//To change body of generated methods, choose Tools | Templates.
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Résultat de l'élève");

        jLabel2.setText("Nom :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel3.setText("..........");

        jLabel4.setText("Prénom :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel5.setText("..........");
        jLabel5.setToolTipText("");

        jLabel6.setText("N*TD :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel7.setText("..........");

        jLabel8.setText("Année Scolaire :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel9.setText("..........");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel10.setText("Niveau");

        jLabel11.setText("Bulletin général de l'année en cours :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Appréciation du 1ère semestre :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Appréciation du 2ème semestre :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Appréciation du 3ème semestre :");

        jLabel15.setForeground(new java.awt.Color(153, 0, 0));
        jLabel15.setText(".........................................................");

        jLabel16.setForeground(new java.awt.Color(153, 0, 0));
        jLabel16.setText(".........................................................");

        jLabel17.setForeground(new java.awt.Color(153, 0, 0));
        jLabel17.setText(".........................................................");

        jLabel18.setText("Appréciation d'anglais :");

        jLabel19.setText("Appréciation de mathématiques :");

        jLabel20.setForeground(new java.awt.Color(255, 0, 51));
        jLabel20.setText(".........................................................");

        jLabel21.setForeground(new java.awt.Color(255, 0, 51));
        jLabel21.setText(".........................................................");

        jLabel22.setText("Appréciation de mathématiques :");

        jLabel23.setForeground(new java.awt.Color(255, 0, 51));
        jLabel23.setText(".........................................................");

        jLabel24.setText("Appréciation d'anglais :");

        jLabel25.setForeground(new java.awt.Color(255, 0, 51));
        jLabel25.setText(".........................................................");

        jLabel26.setText("Appréciation de mathématiques :");

        jLabel27.setForeground(new java.awt.Color(255, 0, 51));
        jLabel27.setText(".........................................................");

        jLabel28.setText("Appréciation d'anglais :");

        jLabel29.setForeground(new java.awt.Color(255, 0, 51));
        jLabel29.setText(".........................................................");

        jLabel30.setText("..");

        jLabel31.setText("..");

        jLabel32.setText("..");

        jLabel33.setText("..");

        jLabel34.setText("..");

        jLabel35.setText("..");

        jButton1.setText("Afficher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jMenu3.setText("Menu");

        jMenuItem1.setText("Retour");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Quitter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(511, 511, 511))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(155, 155, 155)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(134, 134, 134))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel16))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel28))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel23))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(39, 39, 39))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addGap(147, 147, 147)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel14)
                                        .addGap(71, 71, 71)
                                        .addComponent(jLabel17))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(125, 125, 125)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel24))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel29))))
                                .addGap(26, 26, 26)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator3)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(47, 47, 47)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20))
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jLabel21))
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel23))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel26)
                                .addComponent(jLabel27))
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(jLabel29))
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    //String resultat1 = res.Resultat("SELECT ID_classe FROM inscription WHERE ID_personne="+"'"+resultat+"'");
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Interface_recherche f = new Interface_recherche();// TODO add your handling code here:
        f.show();
        dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /**Afficher le nom**/
        jLabel3.setText(nom);// TODO add your handling code here:
        /**Afficher prenom**/
        jLabel5.setText(prenom);
        /**Afficher numéro de TD**/
        Resultset res1 = new Resultset();
        String nom_classe = res1.Resultat("SELECT nom_classe FROM classe WHERE ID_classe = (SELECT ID_classe FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+"))");
        jLabel7.setText(nom_classe);
        /**Afficher Année scolaire**/
        Resultset res2 = new Resultset();
        String ID_anneescolaire = res2.Resultat("SELECT ID_anneescolaire FROM classe WHERE ID_classe = (SELECT ID_classe FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+"))");
        jLabel9.setText(ID_anneescolaire);
        /**Afficher le niveau**/
        Resultset res17 = new Resultset();
        String ID_niveau = res17.Resultat("SELECT ID_niveau FROM classe WHERE ID_classe = (SELECT ID_classe FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+"))");
        Resultset res3 = new Resultset();
        String nom_niveau = res3.Resultat("SELECT nom_niveau FROM niveau WHERE ID_niveau =" + "'" +ID_niveau+ "'");
        jLabel10.setText(nom_niveau);
        /**Enseignement lié au maths**/
        Resultset res16 = new Resultset();
        String ID_maths = res16.Resultat("SELECT ID_enseignement FROM enseignement WHERE ID_discipline='1' AND ID_classe=(SELECT ID_classe FROM classe WHERE nom_classe ="+"'"+nom_classe+"'" +"AND ID_anneescolaire ="+"'"+ID_anneescolaire+"'" +"AND ID_niveau ="+"'"+ID_niveau+"' )");
        /**Enseignement lié a l'anglais**/
        Resultset res18 = new Resultset();
        String ID_anglais = res18.Resultat("SELECT ID_enseignement FROM enseignement WHERE ID_discipline='3' AND ID_classe=(SELECT ID_classe FROM classe WHERE nom_classe ="+"'"+nom_classe+"'" +"AND ID_anneescolaire ="+"'"+ID_anneescolaire+"'" +"AND ID_niveau ="+"'"+ID_niveau+"' )");
        
        /**Afficher le bulletin général**/
        Resultset res4 = new Resultset();
        String appreciation = res4.Resultat("SELECT appreciation FROM bulletin WHERE ID_trimestre = (SELECT ID_trimestre FROM trimestre WHERE numero='1' AND ID_anneescolaire="+"'"+ID_anneescolaire+"'"+" AND ID_inscription = (SELECT ID_inscription FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+")))");
        jLabel15.setText(appreciation);
        Resultset res5 = new Resultset();
        String appreciation1 = res5.Resultat("SELECT appreciation FROM bulletin WHERE ID_trimestre = (SELECT ID_trimestre FROM trimestre WHERE numero='2' AND ID_anneescolaire="+"'"+ID_anneescolaire+"'"+" AND ID_inscription = (SELECT ID_inscription FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+")))");
        jLabel16.setText(appreciation1);
        Resultset res6 = new Resultset();
        String appreciation2 = res6.Resultat("SELECT appreciation FROM bulletin WHERE ID_trimestre = (SELECT ID_trimestre FROM trimestre WHERE numero='3' AND ID_anneescolaire="+"'"+ID_anneescolaire+"'"+" AND ID_inscription = (SELECT ID_inscription FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+")))");
        jLabel17.setText(appreciation2);
        Resultset res7 = new Resultset();
        String appreciation3 = res7.Resultat("SELECT appreciation FROM detailbulletin WHERE ID_enseignement ="+"'"+ID_maths+"' AND ID_bulletin = (SELECT ID_bulletin FROM bulletin WHERE ID_trimestre = (SELECT ID_trimestre FROM trimestre WHERE numero='1' AND ID_anneescolaire="+"'"+ID_anneescolaire+"'"+" AND ID_inscription = (SELECT ID_inscription FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+"))))");
        jLabel20.setText(appreciation3);
        Resultset res8 = new Resultset();
        String appreciation4 = res8.Resultat("SELECT appreciation FROM detailbulletin WHERE ID_enseignement ="+"'"+ID_anglais+"' AND ID_bulletin = (SELECT ID_bulletin FROM bulletin WHERE ID_trimestre = (SELECT ID_trimestre FROM trimestre WHERE numero='1' AND ID_anneescolaire="+"'"+ID_anneescolaire+"'"+" AND ID_inscription = (SELECT ID_inscription FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+"))))");
        jLabel21.setText(appreciation4);
        Resultset res9 = new Resultset();
        String appreciation5 = res9.Resultat("SELECT appreciation FROM detailbulletin WHERE ID_enseignement ="+"'"+ID_maths+"' AND ID_bulletin = (SELECT ID_bulletin FROM bulletin WHERE ID_trimestre = (SELECT ID_trimestre FROM trimestre WHERE numero='2' AND ID_anneescolaire="+"'"+ID_anneescolaire+"'"+" AND ID_inscription = (SELECT ID_inscription FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+"))))");
        jLabel25.setText(appreciation5);
        Resultset res10 = new Resultset();
        String appreciation6 = res10.Resultat("SELECT appreciation FROM detailbulletin WHERE ID_enseignement ="+"'"+ID_anglais+"' AND ID_bulletin = (SELECT ID_bulletin FROM bulletin WHERE ID_trimestre = (SELECT ID_trimestre FROM trimestre WHERE numero='2' AND ID_anneescolaire="+"'"+ID_anneescolaire+"'"+" AND ID_inscription = (SELECT ID_inscription FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+"))))");
        jLabel23.setText(appreciation6);
        Resultset res11 = new Resultset();
        String appreciation7 = res11.Resultat("SELECT appreciation FROM detailbulletin WHERE ID_enseignement ="+"'"+ID_maths+"' AND ID_bulletin = (SELECT ID_bulletin FROM bulletin WHERE ID_trimestre = (SELECT ID_trimestre FROM trimestre WHERE numero='3' AND ID_anneescolaire="+"'"+ID_anneescolaire+"'"+" AND ID_inscription = (SELECT ID_inscription FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+"))))");
        jLabel27.setText(appreciation7);
        Resultset res12 = new Resultset();
        String appreciation8 = res12.Resultat("SELECT appreciation FROM detailbulletin WHERE ID_enseignement ="+"'"+ID_anglais+"' AND ID_bulletin = (SELECT ID_bulletin FROM bulletin WHERE ID_trimestre = (SELECT ID_trimestre FROM trimestre WHERE numero='3' AND ID_anneescolaire="+"'"+ID_anneescolaire+"'"+" AND ID_inscription = (SELECT ID_inscription FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+"))))");
        jLabel29.setText(appreciation8);// TODO add your handling code here:
        /**Recuperer les ID_bulletin de chaque trimestre**/
        Resultset res13 = new Resultset();
        String ID_bulletin1 = res13.Resultat("SELECT ID_bulletin FROM bulletin WHERE ID_trimestre = (SELECT ID_trimestre FROM trimestre WHERE numero='1' AND ID_anneescolaire="+"'"+ID_anneescolaire+"'"+" AND ID_inscription = (SELECT ID_inscription FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+")))");
        Resultset res14 = new Resultset();
        String ID_bulletin2 = res14.Resultat("SELECT ID_bulletin FROM bulletin WHERE ID_trimestre = (SELECT ID_trimestre FROM trimestre WHERE numero='2' AND ID_anneescolaire="+"'"+ID_anneescolaire+"'"+" AND ID_inscription = (SELECT ID_inscription FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+")))");
        Resultset res15 = new Resultset();
        String ID_bulletin3 = res15.Resultat("SELECT ID_bulletin FROM bulletin WHERE ID_trimestre = (SELECT ID_trimestre FROM trimestre WHERE numero='3' AND ID_anneescolaire="+"'"+ID_anneescolaire+"'"+" AND ID_inscription = (SELECT ID_inscription FROM inscription WHERE ID_personne = (SELECT ID_personne FROM personne WHERE nom_personne ="+"'"+nom+"'" +"AND prenom_personne="+"'"+prenom+"'"+")))");
        
        /**Afficher notes**/
        Resultset res19 = new Resultset();
        String notemaths1 = res19.Resultat("SELECT note FROM evaluation WHERE ID_detail = (SELECT ID_detail FROM detailbulletin WHERE ID_bulletin ="+"'"+ID_bulletin1+"'"+" AND ID_enseignement = "+"'"+ID_maths+"')");
        Resultset res20 = new Resultset();
        String notemaths2 = res20.Resultat("SELECT note FROM evaluation WHERE ID_detail = (SELECT ID_detail FROM detailbulletin WHERE ID_bulletin ="+"'"+ID_bulletin2+"'"+" AND ID_enseignement = "+"'"+ID_maths+"')");
        Resultset res21 = new Resultset();
        String notemaths3 = res21.Resultat("SELECT note FROM evaluation WHERE ID_detail = (SELECT ID_detail FROM detailbulletin WHERE ID_bulletin ="+"'"+ID_bulletin3+"'"+" AND ID_enseignement = "+"'"+ID_maths+"')");
        
        Resultset res22 = new Resultset();
        String noteanglais1 = res22.Resultat("SELECT note FROM evaluation WHERE ID_detail = (SELECT ID_detail FROM detailbulletin WHERE ID_bulletin ="+"'"+ID_bulletin1+"'"+" AND ID_enseignement = "+"'"+ID_anglais+"')");
        Resultset res23 = new Resultset();
        String noteanglais2 = res23.Resultat("SELECT note FROM evaluation WHERE ID_detail = (SELECT ID_detail FROM detailbulletin WHERE ID_bulletin ="+"'"+ID_bulletin2+"'"+" AND ID_enseignement = "+"'"+ID_anglais+"')");
        Resultset res24 = new Resultset();
        String noteanglais3 = res24.Resultat("SELECT note FROM evaluation WHERE ID_detail = (SELECT ID_detail FROM detailbulletin WHERE ID_bulletin ="+"'"+ID_bulletin3+"'"+" AND ID_enseignement = "+"'"+ID_anglais+"')");
        
        jLabel30.setText(notemaths1);
        jLabel31.setText(notemaths2);
        jLabel34.setText(notemaths3);
        jLabel32.setText(noteanglais1);
        jLabel33.setText(noteanglais2);
        jLabel35.setText(noteanglais3);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_eleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_eleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_eleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_eleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_eleve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
